tinymce.addI18n('en', {
    'Alert': 'Alert',
    'Alphabet': 'Alphabet',
    'Animals': 'Animals',
    'Arrows': 'Arrows',
    'Astronomy': 'Astronomy',
    'Audio & Video': 'Audio & Video',
    'Automotive': 'Automotive',
    'Autumn': 'Autumn',
    'Beverage': 'Beverage',
    'Brand': 'Brand',
    'Buildings': 'Buildings',
    'Business': 'Business',
    'Camping': 'Camping',
    'Charity': 'Charity',
    'Chart': 'Chart',
    'Charts + Diagrams': 'Charts + Diagrams',
    'Chat': 'Chat',
    'Chess': 'Chess',
    'Childhood': 'Childhood',
    'Clothing': 'Clothing',
    'Clothing + Fashion': 'Clothing + Fashion',
    'Code': 'Code',
    'Coding': 'Coding',
    'Communication': 'Communication',
    'Computers': 'Computers',
    'Connectivity': 'Connectivity',
    'Construction': 'Construction',
    'Currency': 'Currency',
    'Date & Time': 'Date & Time',
    'Design': 'Design',
    'Devices + Hardware': 'Devices + Hardware',
    'Directional': 'Directional',
    'Disaster + Crisis': 'Disaster + Crisis',
    'Editing': 'Editing',
    'Editors': 'Editors',
    'Education': 'Education',
    'Emoji': 'Emoji',
    'Energy': 'Energy',
    'File Type': 'File Type',
    'Files': 'Files',
    'Film + Video': 'Film + Video',
    'Finance': 'Finance',
    'Fitness': 'Fitness',
    'Food': 'Food',
    'Food + Beverage': 'Food + Beverage',
    'Form Control': 'Form Control',
    'Fruits & Vegetables': 'Fruits & Vegetables',
    'Fruits + Vegetables': 'Fruits + Vegetables',
    'Games': 'Games',
    'Gaming': 'Gaming',
    'Gender': 'Gender',
    'Genders': 'Genders',
    'Halloween': 'Halloween',
    'Hand': 'Hand',
    'Hands': 'Hands',
    'Health': 'Health',
    'Holiday': 'Holiday',
    'Holidays': 'Holidays',
    'Hotel': 'Hotel',
    'Household': 'Household',
    'Humanitarian': 'Humanitarian',
    'Icons': 'Icons',
    'Images': 'Images',
    'Interfaces': 'Interfaces',
    'Logistics': 'Logistics',
    'Maps': 'Maps',
    'Maritime': 'Maritime',
    'Marketing': 'Marketing',
    'Mathematics': 'Mathematics',
    'Media Playback': 'Media Playback',
    'Medical': 'Medical',
    'Medical + Health': 'Medical + Health',
    'Miscellaneous': 'Miscellaneous',
    'Money': 'Money',
    'Moving': 'Moving',
    'Music': 'Music',
    'Music + Audio': 'Music + Audio',
    'Nature': 'Nature',
    'No icons matched your search': 'No icons matched your search',
    'Numbers': 'Numbers',
    'Objects': 'Objects',
    'Payment': 'Payment',
    'Payments & Shopping': 'Payments & Shopping',
    'Pharmacy': 'Pharmacy',
    'Photos + Images': 'Photos + Images',
    'Political': 'Political',
    'Punctuation + Symbols': 'Punctuation + Symbols',
    'Religion': 'Religion',
    'Science': 'Science',
    'Science Fiction': 'Science Fiction',
    'Search': 'Search',
    'Security': 'Security',
    'Shapes': 'Shapes',
    'Shopping': 'Shopping',
    'Social': 'Social',
    'Spinner': 'Spinner',
    'Spinners': 'Spinners',
    'Sports': 'Sports',
    'Sports + Fitness': 'Sports + Fitness',
    'Spring': 'Spring',
    'Status': 'Status',
    'Summer': 'Summer',
    'Tabletop Gaming': 'Tabletop Gaming',
    'Text Editor': 'Text Editor',
    'Text Formatting': 'Text Formatting',
    'Time': 'Time',
    'Toggle': 'Toggle',
    'Transportation': 'Transport',
    'Travel': 'Travel',
    'Travel + Hotel': 'Travel + Hotel',
    'User & People': 'User & People',
    'Users + People': 'Users + People',
    'Vehicles': 'Vehicles',
    'Video Player': 'Video Player',
    'Weather': 'Weather',
    'Web Application': 'Web Application',
    'Winter': 'Winter',
    'Writing': 'Writing'
});
